/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e75197f06e8563f32296087
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
// Import Services
import { VenderService } from '../../services/vender.service';
// Import Models
import { Vender } from '../../domain/market_db/vender';

// START - USED SERVICES
/**
* venderService.create
*	@description CRUD ACTION create
*
* venderService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
* venderService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id resource
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a Vender
 */
@Component({
    selector: 'app-vender-edit',
    templateUrl: 'vender-edit.component.html',
    styleUrls: ['vender-edit.component.css']
})
export class VenderEditComponent implements OnInit {
    item: Vender;
    
    model: Vender;
    formValid: Boolean;

    constructor(
    private venderService: VenderService,
    private route: ActivatedRoute,
    private location: Location) {
        // Init item
        this.item = new Vender();
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.venderService.get(id).subscribe(item => this.item = item);
            }
            // Get relations
        });
    }


    /**
     * Save Vender
     *
     * @param {boolean} formValid Form validity check
     * @param Vender item Vender to save
     */
    save(formValid: boolean, item: Vender): void {
        this.formValid = formValid;
        if (formValid) {
            if (item._id) {
                this.venderService.update(item).subscribe(data => this.goBack());
            } else {
                this.venderService.create(item).subscribe(data => this.goBack());
            } 
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }


}



