/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e75197f06e8563f32296087
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
// Import Services
import { ComprarService } from '../../services/comprar.service';
// Import Models
import { Comprar } from '../../domain/market_db/comprar';

// START - USED SERVICES
/**
* comprarService.create
*	@description CRUD ACTION create
*
* comprarService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
* comprarService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id resource
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a Comprar
 */
@Component({
    selector: 'app-comprar-edit',
    templateUrl: 'comprar-edit.component.html',
    styleUrls: ['comprar-edit.component.css']
})
export class ComprarEditComponent implements OnInit {
    item: Comprar;
    
    model: Comprar;
    formValid: Boolean;

    constructor(
    private comprarService: ComprarService,
    private route: ActivatedRoute,
    private location: Location) {
        // Init item
        this.item = new Comprar();
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.comprarService.get(id).subscribe(item => this.item = item);
            }
            // Get relations
        });
    }


    /**
     * Save Comprar
     *
     * @param {boolean} formValid Form validity check
     * @param Comprar item Comprar to save
     */
    save(formValid: boolean, item: Comprar): void {
        this.formValid = formValid;
        if (formValid) {
            if (item._id) {
                this.comprarService.update(item).subscribe(data => this.goBack());
            } else {
                this.comprarService.create(item).subscribe(data => this.goBack());
            } 
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }


}



